export type Product = {
  id: number
  name: string
  description: string
  price: number
  category: 'Vêtements' | 'Électronique' | 'Maison' | 'Sport'
  rating: number
  reviewCount: number
  colors: string[]
  sizes?: string[]
  stock: number
  imageIds: number[]
  badge?: string
  isNew?: boolean
}

export const products: Product[] = [
  {
    id: 1,
    name: 'Veste en Cuir Milano',
    description: 'Veste en cuir véritable avec doublure en soie. Coupe ajustée moderne, fermeture éclair YKK. Idéale pour les soirées et les sorties décontractées.',
    price: 289.99,
    category: 'Vêtements',
    rating: 4.8,
    reviewCount: 124,
    colors: ['#1a1a1a', '#8B4513', '#2c3e50'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 15,
    imageIds: [11, 12, 13, 14],
    badge: 'Bestseller',
  },
  {
    id: 2,
    name: 'Sneakers Urban Pro',
    description: 'Baskets urbaines avec semelle en mousse à mémoire de forme. Tige en mesh respirant, semelle extérieure grip antidérapante.',
    price: 119.99,
    category: 'Sport',
    rating: 4.6,
    reviewCount: 88,
    colors: ['#ffffff', '#1a1a1a', '#e74c3c'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 32,
    imageIds: [21, 22, 23, 24],
    isNew: true,
  },
  {
    id: 3,
    name: 'Écouteurs Sans-Fil AirMax X3',
    description: 'Écouteurs à réduction de bruit active. Autonomie 32h, charge rapide 10 min = 2h d'écoute. Qualité audio Hi-Fi avec égaliseur intégré.',
    price: 179.99,
    category: 'Électronique',
    rating: 4.9,
    reviewCount: 256,
    colors: ['#1a1a1a', '#c0c0c0', '#1e3a5f'],
    stock: 45,
    imageIds: [31, 32, 33, 34],
    badge: 'Top Vente',
  },
  {
    id: 4,
    name: 'Lampe de Bureau Architecte LED',
    description: 'Lampe architecte articulée avec 5 niveaux de luminosité et 3 températures de couleur. Chargeur USB-C intégré. Bras en aluminium anodisé.',
    price: 89.99,
    category: 'Maison',
    rating: 4.7,
    reviewCount: 67,
    colors: ['#1a1a1a', '#c0c0c0', '#d4af37'],
    stock: 23,
    imageIds: [41, 42, 43, 44],
  },
  {
    id: 5,
    name: 'Pull Col Roulé Cachemire',
    description: 'Pull en cachemire 100% mérinos grade A. Douceur incomparable, régulation thermique naturelle. Disponible en plusieurs coloris élégants.',
    price: 159.99,
    category: 'Vêtements',
    rating: 4.5,
    reviewCount: 43,
    colors: ['#1a1a1a', '#f5f5f0', '#8B4513', '#2c3e50'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 18,
    imageIds: [51, 52, 53, 54],
  },
  {
    id: 6,
    name: 'Montre Connectée FitPro 5',
    description: 'Montre sport avec GPS intégré, capteur cardio 24h, SpO2, suivi du sommeil. Étanche 5ATM. Autonomie 7 jours. Compatible iOS & Android.',
    price: 249.99,
    category: 'Électronique',
    rating: 4.4,
    reviewCount: 189,
    colors: ['#1a1a1a', '#c0c0c0', '#e74c3c'],
    stock: 27,
    imageIds: [61, 62, 63, 64],
    isNew: true,
  },
  {
    id: 7,
    name: 'Tapis de Yoga Eco Premium',
    description: 'Tapis de yoga en caoutchouc naturel certifié éco. Épaisseur 6mm, surface antidérapante double face. Marquages d'alignement imprimés.',
    price: 79.99,
    category: 'Sport',
    rating: 4.8,
    reviewCount: 112,
    colors: ['#2ecc71', '#9b59b6', '#1a1a1a'],
    stock: 54,
    imageIds: [71, 72, 73, 74],
  },
  {
    id: 8,
    name: 'Cafetière à Piston Barista',
    description: 'French press en verre borosilicaté avec cadre inox brossé. Capacité 1L, filtre triple épaisseur inoxydable. Design primé Red Dot 2023.',
    price: 59.99,
    category: 'Maison',
    rating: 4.6,
    reviewCount: 78,
    colors: ['#1a1a1a', '#c0c0c0'],
    stock: 40,
    imageIds: [81, 82, 83, 84],
  },
  {
    id: 9,
    name: 'Jean Slim Stretch Comfort',
    description: 'Jean slim avec tissu stretch 4 directions pour un confort maximal. Lavage stone-washed artisanal. Coupe ajustée aux cuisses et chevilles.',
    price: 89.99,
    category: 'Vêtements',
    rating: 4.3,
    reviewCount: 56,
    colors: ['#1e3a5f', '#1a1a1a', '#808080'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 29,
    imageIds: [91, 92, 93, 94],
  },
  {
    id: 10,
    name: 'Clavier Mécanique RGB ProType',
    description: 'Clavier mécanique TKL avec switches Cherry MX Red. Rétroéclairage RGB par touche, 16M couleurs. Anti-ghosting 100%. USB-C amovible.',
    price: 139.99,
    category: 'Électronique',
    rating: 4.7,
    reviewCount: 203,
    colors: ['#1a1a1a', '#f5f5f0'],
    stock: 21,
    imageIds: [101, 102, 103, 104],
    badge: 'Pro',
  },
  {
    id: 11,
    name: 'Vélo de Appartement X-Ride',
    description: 'Vélo stationnaire magnétique 16 niveaux de résistance. Écran LCD, capteur cardiaque intégré, guidon et selle réglables. Silencieux et compact.',
    price: 399.99,
    category: 'Sport',
    rating: 4.5,
    reviewCount: 34,
    colors: ['#1a1a1a', '#e74c3c'],
    stock: 8,
    imageIds: [111, 112, 113, 114],
  },
  {
    id: 12,
    name: 'Coussin Décoratif Velours',
    description: 'Coussin en velours côtelé avec rembourrage en fibres recyclées. Fermeture invisible, housse lavable. Collection Automne-Hiver 2024.',
    price: 34.99,
    category: 'Maison',
    rating: 4.2,
    reviewCount: 29,
    colors: ['#8B4513', '#2c3e50', '#1a1a1a', '#c0c0c0'],
    stock: 67,
    imageIds: [121, 122, 123, 124],
  },
  {
    id: 13,
    name: 'Blouson Technique Imperméable',
    description: 'Veste outdoor en Pertex® Shield 3 couches, imperméabilité 20 000mm. Coutures soudées, zip ventilation, capuche ajustable. Compressible.',
    price: 219.99,
    category: 'Vêtements',
    rating: 4.9,
    reviewCount: 92,
    colors: ['#1e3a5f', '#1a1a1a', '#2ecc71'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 14,
    imageIds: [131, 132, 133, 134],
    badge: 'Nouveau',
    isNew: true,
  },
  {
    id: 14,
    name: 'Enceinte Bluetooth Nomade',
    description: 'Enceinte portative IP67, autonomie 24h. Son 360° avec basses profondes. Charge solaire et USB-C. Compatible avec l'assistant vocal.',
    price: 99.99,
    category: 'Électronique',
    rating: 4.6,
    reviewCount: 148,
    colors: ['#1a1a1a', '#2ecc71', '#e74c3c'],
    stock: 38,
    imageIds: [141, 142, 143, 144],
  },
  {
    id: 15,
    name: 'Gants de Boxe Pro Fighter',
    description: 'Gants de boxe en cuir véritable, mousse haute densité triple épaisseur. Velcro renforcé, poignet stabilisateur. Homologués compétition.',
    price: 74.99,
    category: 'Sport',
    rating: 4.7,
    reviewCount: 61,
    colors: ['#e74c3c', '#1a1a1a', '#1e3a5f'],
    stock: 22,
    imageIds: [151, 152, 153, 154],
  },
  {
    id: 16,
    name: 'Miroir Mural avec Éclairage LED',
    description: 'Miroir Hollywood avec 14 ampoules LED à intensité variable. Température de couleur réglable. Cadre en laiton brossé, fixation murale incluse.',
    price: 149.99,
    category: 'Maison',
    rating: 4.4,
    reviewCount: 45,
    colors: ['#d4af37', '#c0c0c0', '#1a1a1a'],
    stock: 12,
    imageIds: [161, 162, 163, 164],
  },
]

export const categories = ['Vêtements', 'Électronique', 'Maison', 'Sport'] as const

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductImageUrl(seed: number, width = 400, height = 400): string {
  return `https://picsum.photos/seed/${seed}/${width}/${height}`
}
